/** ENVIRONMENT */
export const SETUP_ENVIRONMENT = 'SETUP_ENVIRONMENT';

/** SESSION */
export const STORE_SESSION = 'STORE_SESSION';

/** EVENTBUS */
export const EVENT_BUS_CONNECT = 'EVENT_BUS_CONNECT';
export const EVENT_BUS_DISCONNECT = 'EVENT_BUS_DISCONNECT';

/** TOKEN */
export const STORE_DEVICE_TOKEN = 'STORE_DEVICE_TOKEN';
export const STORE_APNS_TOKEN = 'STORE_APNS_TOKEN';
export const STORE_VOIP_TOKEN = 'STORE_VOIP_TOKEN';

/** LOCALE */
export const CHANGE_DEVICE_LOCALE = 'CHANGE_DEVICE_LOCALE';

/** ONBOARDING SCREEN */
export const HIDE_ONBOARDING = 'HIDE_ONBOARDING';

/** ALERT DIALOG */
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

/** BOTTOMTAB */
export const SET_POSITION_BOTTOM_TAB = 'SET_POSITION_BOTTOM_TAB';

/** ACTIVITY TRACKING */
export const TOGGLE_ACTIVITY_TRACKING = 'TOGGLE_ACTIVITY_TRACKING';
export const STORE_ACTIVITY_TRACKING = 'STORE_ACTIVITY_TRACKING';
export const UPDATE_ACTIVITY_TRACKING = 'UPDATE_ACTIVITY_TRACKING';

/** SOCKJS */
export const SOCKJS_INSTANCE = 'SOCKJS_INSTANCE';

/** EVENTBUS */
export const EVENTBUS_INSTANCE = 'EVENTBUS_INSTANCE';
